In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import gmaps_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Kampene,-3.6000,26.6667,73.83,88,100,1.77,CD,2022-01-08 17:19:09
1,1,Kapaa,22.0752,-159.3190,69.78,82,100,9.22,US,2022-01-08 17:17:40
2,2,Jamestown,42.0970,-79.2353,25.09,47,0,7.00,US,2022-01-08 17:14:24
3,3,Safford,32.8340,-109.7076,62.11,61,0,3.44,US,2022-01-08 17:18:56
4,4,Punta Arenas,-53.1500,-70.9167,57.31,44,0,37.98,CL,2022-01-08 17:19:11

In [3]:
city_data_df.dtypes

City_ID         int64
City           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
Country        object
Date           object
dtype: object

In [4]:
city_data_df.describe()

,City_ID,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
count,41.000000,41.000000,41.000000,41.000000,41.000000,41.000000,41.000000
mean,20.000000,16.264978,16.851168,47.559756,71.731707,60.707317,12.261707
std,11.979149,38.629921,96.055754,32.605231,18.701637,37.419409,8.984224
min,0.000000,-54.800000,-159.319000,-34.580000,22.000000,0.000000,1.590000
25%,10.000000,-19.550000,-58.650200,26.260000,63.000000,28.000000,5.010000
50%,20.000000,22.075200,26.666700,57.310000,74.000000,75.000000,9.550000
75%,30.000000,47.666600,97.033300,73.830000,84.000000,98.000000,17.520000
max,40.000000,73.506900,169.266700,91.090000,100.000000,100.000000,37.980000

In [5]:
city_data_df = city_data_df[city_data_df['Max Temp'] >= 0]

In [6]:
city_data_df.describe()

,City_ID,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
count,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000
mean,19.243243,10.971154,19.188897,55.132162,69.945946,62.594595,12.551081
std,11.748299,36.891159,93.280109,23.785582,18.236023,37.477741,9.338018
min,0.000000,-54.800000,-159.319000,6.240000,22.000000,0.000000,1.590000
25%,10.000000,-23.120300,-52.731400,32.790000,61.000000,28.000000,5.010000
50%,19.000000,19.750000,26.666700,61.050000,73.000000,75.000000,9.550000
75%,29.000000,39.466700,93.450000,73.870000,83.000000,100.000000,17.810000
max,40.000000,73.506900,169.266700,91.090000,97.000000,100.000000,37.980000

In [7]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=gmaps_key)

In [8]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp)

In [10]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [11]:
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

In [12]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# 6.5.3 get Vacation Criteria

In [14]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [15]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
11,11,Beloha,-25.1667,45.0500,76.15,79,69,17.81,MG,2022-01-08 17:19:15
12,12,Bredasdorp,-34.5322,20.0403,76.28,83,5,21.85,ZA,2022-01-08 17:19:16
14,14,Rikitea,-23.1203,-134.9692,78.12,81,100,20.78,PF,2022-01-08 17:17:52
20,20,Hithadhoo,-0.6000,73.0833,82.11,74,25,5.39,MV,2022-01-08 17:17:36
23,23,Cayenne,4.9333,-52.3333,84.24,73,75,5.01,GF,2022-01-08 17:19:22
26,26,Isangel,-19.5500,169.2667,79.38,89,54,14.70,VU,2022-01-08 17:19:25
29,29,Lambarene,-0.7001,10.2406,84.61,70,83,3.31,GA,2022-01-08 17:19:27
32,32,Touros,-5.1989,-35.4608,88.70,60,89,13.82,BR,2022-01-08 17:15:04

In [16]:
preferred_cities_df.count()

City_ID       8
City          8
Lat           8
Lng           8
Max Temp      8
Humidity      8
Cloudiness    8
Wind Speed    8
Country       8
Date          8
dtype: int64

In [17]:
# 6.5.4 Map Vacation Criteria

In [18]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

          City Country  Max Temp      Lat       Lng Hotel Name
11      Beloha      MG     76.15 -25.1667   45.0500
12  Bredasdorp      ZA     76.28 -34.5322   20.0403
14     Rikitea      PF     78.12 -23.1203 -134.9692
20   Hithadhoo      MV     82.11  -0.6000   73.0833
23     Cayenne      GF     84.24   4.9333  -52.3333
26     Isangel      VU     79.38 -19.5500  169.2667
29   Lambarene      GA     84.61  -0.7001   10.2406
32      Touros      BR     88.70  -5.1989  -35.4608

In [19]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": gmaps_key
}

In [20]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": gmaps_key
}

In [21]:
# Set the parameters to search for a hotel in Paris.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": gmaps_key,
    "location": "48.8566, 2.3522"}
# Use base URL to search for hotels in Paris.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()

hotels

{'html_attributions': [],
 'next_page_token': 'Aap_uEA1RB1NlkdBL6qjRm9fBalmDgvvuiDme3rzH9VRrK0XtjAg4iS0FDKO3ThDsu6-FgYlThHh0_q8Uxh7dE6pZ2jyT_ioALN-ZLJikYPS78Q3zFG34hZ4cMTRuioRSzLlheddPmuN_Zwy-7eVC9-EwcSKVtI21ZT1NwWOqzlj7gaZ5KKNDWN6DtsPTSsiUZcffeL2ORZz2kTOoZmmzQrBlot7LZ_ybvc9DwG9BNgs-SyFOVPub_plJGyOvZiFFGJYwInMNe-pBqykGMhOs-0crUem5COh8he30BiwtBcBTHBY3X3mcexaBOr5imH5hm5inTbe1vqHs6bRILw5jqqsLusCw4pz32jhD1hmjtP4GbEtch5FDs80qQxdY1a2MyHQ9X-MD18mQ8D9-7j4HFmMIaZXlSnprwdFK5M6yibpOymf6Ong706-p1z8',
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8581126, 'lng': 2.3529277},
    'viewport': {'northeast': {'lat': 48.8594360302915,
      'lng': 2.354355480291502},
     'southwest': {'lat': 48.8567380697085, 'lng': 2.351657519708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Duo',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3840,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107554201425443337224">Hôtel Duo</a>'],
     'photo_reference': 'Aap_uEC92Y5tYYk4GH28pyx8YqVjQvc4UU-EgojnIzZDi0UGSH_oe-v7a96mSlcVWGf3QTWOn5UJdCw955YbbQdjb3IrYDD5aCPHpVJ_wYk6IWisE6Ry0qkDHMQm2reDd1wiUpbx-8w89LX4-s_WjYGtcSdhLQsVXAc2RAa2e83wDZa_9IOa',
     'width': 5760}],
   'place_id': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'plus_code': {'compound_code': 'V953+65 Paris, France',
    'global_code': '8FW4V953+65'},
   'rating': 4.2,
   'reference': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'scope': 'GOOGLE',
   'types': ['night_club',
    'spa',
    'lodging',
    'bar',
    'gym',
    'health',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 315,
   'vicinity': '11 Rue du Temple, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8582861, 'lng': 2.3464944},
    'viewport': {'northeast': {'lat': 48.85954748029151,
      'lng': 2.347782830291502},
     'southwest': {'lat': 48.85684951970851, 'lng': 2.345084869708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Britannique - Paris Centre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1426,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108984000175492464929">Hôtel Britannique - Paris Centre</a>'],
     'photo_reference': 'Aap_uEDXYBvqw6WbywT0yimQ8GQlSMJrpAWGetmeKKXwlazjUA-ZUI9Te10pCiEntyNxSiLleWhEzQbY5vWumyRULeM8E4pl1HEQcgE_lNCntTVlvXVpEhyBWtlhL3og0wozbVTHCL3ZxJgJ2s3fG0I8A1j7tHlWg_-TNhtq5ncK9FJ71fcj',
     'width': 1476}],
   'place_id': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'plus_code': {'compound_code': 'V85W+8H Paris, France',
    'global_code': '8FW4V85W+8H'},
   'rating': 4.6,
   'reference': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 667,
   'vicinity': '20 Avenue Victoria, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8606655, 'lng': 2.3469293},
    'viewport': {'northeast': {'lat': 48.8617746302915,
      'lng': 2.347927730291502},
     'southwest': {'lat': 48.8590766697085, 'lng': 2.345229769708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Citadines Les Halles Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 853,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102565262508115704337">Citadines Les Halles Paris (Apart hotel Paris)</a>'],
     'photo_reference': 'Aap_uEDDt4bAdc6GYzatjYJQDJqY-T3754ZdN4xjNmIUHbkSQALnzSefzM_XCa47k22j9xLV4RDq-H3rMFkxjI3hQZiA8dQyirntFzWFh914yWDMmaiFEOMN3Q0VaLn_BFkjYhtZi_17yoj7coHQ64UXUyyol-0aLMJ7BjisRxaURKl1pb9K',
     'width': 1280}],
   'place_id': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'plus_code': {'compound_code': 'V86W+7Q Paris, France',
    'global_code': '8FW4V86W+7Q'},
   'rating': 4.1,
   'reference': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 883,
   'vicinity': '4 Rue des Innocents, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8607658, 'lng': 2.3465318},
    'viewport': {'northeast': {'lat': 48.8620584302915,
      'lng': 2.347692880291501},
     'southwest': {'lat': 48.85936046970851, 'lng': 2.344994919708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Novotel Paris Les Halles',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111815616573299411056">Novotel Paris Les Halles</a>'],
     'photo_reference': 'Aap_uEDWLjeCjSBBUn96GDn5n8BUvLnCu_Se6GQLznwpj14KFA8Bjf6SisCiwqu75XTw0GdFPPrxnyP_tcU4DtnRUNxoAJrqbuEmOKtNa5myG35weR-X-0iLSc4mWiZnWWuqbmS0f4Fv348xmVL7O60IpgE4Y5tSrouIFK-UnNPCMJryrbI8',
     'width': 3000}],
   'place_id': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'plus_code': {'compound_code': 'V86W+8J Paris, France',
    'global_code': '8FW4V86W+8J'},
   'rating': 4.4,
   'reference': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2339,
   'vicinity': '8 Place Marguerite de Navarre, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.860352, 'lng': 2.3440948},
    'viewport': {'northeast': {'lat': 48.86165553029149,
      'lng': 2.345549080291502},
     'southwest': {'lat': 48.8589575697085, 'lng': 2.342851119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Ducs de Bourgogne',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1390,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101411638353598558320">Hôtel Ducs de Bourgogne</a>'],
     'photo_reference': 'Aap_uEDPdvVcqv7CL_0ttgFrtC1TvjB8Hn5CQaSD7Pn5-37luih8_9cwkeD3FbvE8GVr0zr5gCVOtGRNxq4IUOqCsBtXeBH-tvZJYJK3xIbFTlZKj5No8zafam8kE08HFeMb5nv3AHccLxmXHiuWpgC9Bqxd_sCXF7c1jOJSNhPBud44CGPy',
     'width': 2048}],
   'place_id': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'plus_code': {'compound_code': 'V86V+4J Paris, France',
    'global_code': '8FW4V86V+4J'},
   'rating': 4.5,
   'reference': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 284,
   'vicinity': '19 Rue du Pont Neuf, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8555091, 'lng': 2.3408736},
    'viewport': {'northeast': {'lat': 48.8569076302915,
      'lng': 2.342319280291502},
     'southwest': {'lat': 48.8542096697085, 'lng': 2.339621319708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Citadines Saint-Germain-des-Prés Paris (Apart hotel Paris)',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4480,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113188832595116816387">Citadines Saint-Germain-des-Prés Paris</a>'],
     'photo_reference': 'Aap_uEDIfvwCsgKSeUDEAb838t30Rmr508ct2AVrzHNTwyEztqe0P5mlVWYcz3TfX36-BSus35QtanuSjWfBQsea6TB8UfoAEEjf_ju9f8t3kaLgx20jNEAFGutfHK5vkvD7eGPi7bD2o0hm00uOezZrU-YqhPH_I_CViyApVGSh1OOnrl9w',
     'width': 6720}],
   'place_id': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'plus_code': {'compound_code': 'V84R+68 Paris, France',
    'global_code': '8FW4V84R+68'},
   'rating': 4.3,
   'reference': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 720,
   'vicinity': '53 ter Quai des Grands Augustins, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8663519, 'lng': 2.3606461},
    'viewport': {'northeast': {'lat': 48.86775308029149,
      'lng': 2.361905130291502},
     'southwest': {'lat': 48.8650551197085, 'lng': 2.359207169708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Paris France Hôtel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2673,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102332962500946068613">Paris France Hôtel</a>'],
     'photo_reference': 'Aap_uEB8yCBrTB8ufBWMHiVkk_rbtqLlPv-VvXT7FCZ-lLnyW_-ubNBqHamM5_w8f_5PQl6VR8Zr2lLt3QCtqXUu403Z1OmYFg3LC9VfByIfBLAL_kCGoh5fEXdOjw2rRB1sAJrm6RX4sQpMAnYG9C0OFJitDV3eVqlMDoULL8vbTbeUGB_1',
     'width': 3463}],
   'place_id': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'plus_code': {'compound_code': 'V986+G7 Paris, France',
    'global_code': '8FW4V986+G7'},
   'rating': 4.3,
   'reference': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 402,
   'vicinity': '72 Rue de Turbigo, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86386539999999, 'lng': 2.3325488},
    'viewport': {'northeast': {'lat': 48.8650759802915,
      'lng': 2.333775730291502},
     'southwest': {'lat': 48.8623780197085, 'lng': 2.331077769708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hotel Regina Louvre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3700,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109908333790946649027">Hôtel Regina Louvre</a>'],
     'photo_reference': 'Aap_uEBcNvRGwN_h25WEn25dDySEIJAyhTjhnRKW9g-VwIx6sOAYBZ_5DS4whZmy3tAXs8bgdILFz0eO6IYOfmQwttOWH01c0T5oLcrb4GKSa3l-l_hrYjPvriY_Nnxnz3GOKofN6wic_TECLJ24HIJjmig3sVZBFxgRgTZHWXjFQuJ22vRm',
     'width': 5550}],
   'place_id': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'plus_code': {'compound_code': 'V87M+G2 Paris, France',
    'global_code': '8FW4V87M+G2'},
   'rating': 4.5,
   'reference': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 509,
   'vicinity': '2 Place des Pyramides, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.84795229999999, 'lng': 2.370869},
    'viewport': {'northeast': {'lat': 48.8492035302915,
      'lng': 2.372290080291501},
     'southwest': {'lat': 48.8465055697085, 'lng': 2.369592119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'ibis Paris Gare de Lyon Ledru Rollin 12ème',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2048,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101181280085797863615">Kevin Nguyen</a>'],
     'photo_reference': 'Aap_uECJLUM-CEfTjKYtlcaIHoG1BtAbSHtOZ5uNfbkf0s2Sflua48Im58d9ptPNAkBRPMtvETGMluCFCdnCujRH9XKSFkHsL5CMv0aQJQWOffSiErOLXEd3aAAtdlvYo3sNjufsqux6U7SHY3eopNZvkBpKvG7IRDcHRCp0Jvv8Ow1CgrKF',
     'width': 1536}],
   'place_id': 'ChIJ9RNxcQNy5kcRnZJ4vsuXcow',
   'plus_code': {'compound_code': 'R9XC+58 Paris, France',
    'global_code': '8FW4R9XC+58'},
   'rating': 4.1,
   'reference': 'ChIJ9RNxcQNy5kcRnZJ4vsuXcow',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 856,
   'vicinity': '41/43 Avenue Ledru Rollin, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8710647, 'lng': 2.34991},
    'viewport': {'northeast': {'lat': 48.87241888029151,
      'lng': 2.351188530291502},
     'southwest': {'lat': 48.86972091970851, 'lng': 2.348490569708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel des Comédies Paris',
   'photos': [{'height': 4000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114696623290303183213">Noble</a>'],
     'photo_reference': 'Aap_uEAxwOfERX7Nm1tlaSByQQtmCVVeeQqG8sJBTo7Hml86pod48lI-Il_sg_5hqkIkS4QBWZSxijGtHN0qh86b0ZN_F-1Ogkcq-xvg4oDr6YUa-irl4U2PWSPCs5zspyJRq235dkdMdug0wgqJNggAUtsIyEBR-85nY9_SwGKJ_6oz9Xbk',
     'width': 3000}],
   'place_id': 'ChIJn6ginxZu5kcRmAEK0OHm0cI',
   'plus_code': {'compound_code': 'V8CX+CX Paris, France',
    'global_code': '8FW4V8CX+CX'},
   'rating': 4.3,
   'reference': 'ChIJn6ginxZu5kcRmAEK0OHm0cI',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 200,
   'vicinity': "8 Rue d'Hauteville, Paris"},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.84754640000001, 'lng': 2.3718722},
    'viewport': {'northeast': {'lat': 48.8488820802915,
      'lng': 2.373123430291502},
     'southwest': {'lat': 48.8461841197085, 'lng': 2.370425469708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel De France Gare de Lyon Bastille',
   'photos': [{'height': 787,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117462031751048846575">Hôtel De France Gare de Lyon Bastille</a>'],
     'photo_reference': 'Aap_uEA4tKdmqS-B4jY9JlgCeR3-6At5q3hq46AOY28RbIyr54SYnzJE1U5ZEa_NjDFY5yT7BzABzR-X7N0SnoEeYXPVlDeNLpL3xpf8eTyNGNMTTu4mZOj7fT5aJmkVGwYQczkp9ND9KND3YKIB3d8h3yZhbGFGwW9y_Qgfxe48_hhB-n1A',
     'width': 1181}],
   'place_id': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'plus_code': {'compound_code': 'R9XC+2P Paris, France',
    'global_code': '8FW4R9XC+2P'},
   'rating': 3.3,
   'reference': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 383,
   'vicinity': '12 Rue de Lyon, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8717386, 'lng': 2.3447052},
    'viewport': {'northeast': {'lat': 48.8731374802915,
      'lng': 2.346059980291502},
     'southwest': {'lat': 48.8704395197085, 'lng': 2.343362019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Prélude Opéra Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2448,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/106224131803115407650">Marcin Marczak</a>'],
     'photo_reference': 'Aap_uEBdkZq9XCebVLsl1xQfVxZopPoP8sm5FAYNiFRNbz_5A6X8gxGSWUkmocg7aizzF6jHQchgEnY4V9rww14wGElJ38bqhE5k7BKuw0n5zJq9xu8XO5tlsSaOpeRgaRuIRYjp-PtHoc4KyK6juCwu69lRAtaVDAwySZqvAqy1g_G-M5cv',
     'width': 3264}],
   'place_id': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'plus_code': {'compound_code': 'V8CV+MV Paris, France',
    'global_code': '8FW4V8CV+MV'},
   'rating': 4.2,
   'reference': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 403,
   'vicinity': '8 Cité Bergère, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8423434, 'lng': 2.3632087},
    'viewport': {'northeast': {'lat': 48.8436624802915,
      'lng': 2.364700930291502},
     'southwest': {'lat': 48.8409645197085, 'lng': 2.362002969708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Libertel Austerlitz Jardin des Plantes',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4480,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114802271282641766772">Hôtel Libertel Austerlitz Jardin des Plantes</a>'],
     'photo_reference': 'Aap_uEDytZeaSQZN84VgzHFd2vh0dlsQPi9rd2OC2U5bKwSAwYd4LBe2jtkpQPn4gUSoiA_iYdncEShWa8VYmCSYfwntFnPqFMfI370NicqlZfxsHRckaF5eqsQNPrgVxSLUw8GD4msRZvnR7MocGqj_GH-m1DhMv9Bn5Or0sAWbvxv5GyaG',
     'width': 6720}],
   'place_id': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'plus_code': {'compound_code': 'R9R7+W7 Paris, France',
    'global_code': '8FW4R9R7+W7'},
   'rating': 3.9,
   'reference': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 461,
   'vicinity': "12 Boulevard de l'Hôpital, Paris"},
  {'business_status': 'CLOSED_TEMPORARILY',
   'geometry': {'location': {'lat': 48.8642974, 'lng': 2.3308142},
    'viewport': {'northeast': {'lat': 48.8655789302915,
      'lng': 2.332153980291502},
     'southwest': {'lat': 48.8628809697085, 'lng': 2.329456019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Saint James Albany Paris Hôtel Spa',
   'permanently_closed': True,
   'photos': [{'height': 400,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108570400659068256718">Saint James Albany Paris Hôtel Spa</a>'],
     'photo_reference': 'Aap_uECcEwxTsPVIFCDKi6f3LPq56W8U6_Kq2cg2qZCXdIvav_B0VieCLSItfwMknLsYlV0DQQuofb__jDBlVMqghjP72ULDe10EasuKgOnKPb999kT0hMUQelVZy-NdD49XwL41xnp6Yh3RTfApKzQbKUOLURaesmRAWRmqw9R4_Ed0Ret6',
     'width': 600}],
   'place_id': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'plus_code': {'compound_code': 'V87J+P8 Paris, France',
    'global_code': '8FW4V87J+P8'},
   'rating': 4,
   'reference': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 1075,
   'vicinity': '202 Rue de Rivoli, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.87110329999999, 'lng': 2.3389728},
    'viewport': {'northeast': {'lat': 48.8724169302915,
      'lng': 2.340369280291502},
     'southwest': {'lat': 48.8697189697085, 'lng': 2.337671319708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Icône',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1066,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108137830440312077288">Hôtel Icône</a>'],

In [22]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.

In [23]:
# Grab the first hotel from the results and store the name.
try:
    hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
except (IndexError):
    print("Hotel not found... skipping.")

In [24]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [25]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [26]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [27]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [28]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [29]:
hotel_df.head()

          City Country  Max Temp      Lat       Lng                Hotel Name
11      Beloha      MG     76.15 -25.1667   45.0500
12  Bredasdorp      ZA     76.28 -34.5322   20.0403  Bredasdorp Country Manor
14     Rikitea      PF     78.12 -23.1203 -134.9692           People ThankYou
20   Hithadhoo      MV     82.11  -0.6000   73.0833         Scoop Guest House
23     Cayenne      GF     84.24   4.9333  -52.3333           Hôtel Le Dronmi